nix/server: use nodejs-12
Due to
```
TimeoutError: Knex: Timeout acquiring a connection.
The pool is probably full. Are you missing a .transacting(trx) call?
```

See https://github.com/knex/knex/issues/2820

Should go away and allow us to use nodejs-14
if `pg` package is bumped to `8.x`.